name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.4.0
        with:
          node-version: 12.x

      - name: Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Deploy to NPM
        id: semantic
        uses: cycjimmy/semantic-release-action@v2
        with:
          semantic_version: 17
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN_SEMANTIC_RELEASE }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
